[project]
name = "drone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "djitellopy>=2.5.0",
    "opencv-contrib-python>=4.12.0.88",
    "pynput>=1.8.1",
]

[tool.uv.workspace]
members = [
    "ArUcomarker",
]
